Attempt to output emoji's in pipeline.

diff --git a/.forgejo/workflows/push.yaml b/.forgejo/workflows/push.yaml
--- a/.forgejo/workflows/push.yaml
+++ b/.forgejo/workflows/push.yaml
@@ -8,16 +8,16 @@ jobs:
       - name: Test for tidy, fmt, vet
         run: |
           echo '--- Begin "go mod tidy"'
-          if go mod tidy -diff; then echo '--- "go.mod" is tidy.'; else echo "--- Exit code: $?, "go.mod" is not tidy!"; fi
+          if go mod tidy -diff; then printf -- '--- \U0001f7e9 "go.mod" is tidy.'; else printf -- "--- \U0001f7e5 Exit code: $?, "go.mod" is not tidy!"; fi
           echo '--- Begin "gofmt -l"'
           out=$(gofmt -l .)
           exit_code=$?
-          if test -z $out; then echo '--- Source files are formatted.'; else echo -e "Unformatted files:\n$out\n--- Exit code: $exit_code, Source is unformatted!"; exit $exit_code; fi
+          if test -z $out; then printf -- '--- \U0001f7e9 Source files are formatted.'; else echo -e "Unformatted files:\n$out; printf -- "--- \U0001f7e5 Exit code: $exit_code, Source is unformatted!"; exit $exit_code; fi
           echo '--- Begin "go vet ./..."'
-          if go vet ./...; then echo '--- No suspicious constructs found.'; else echo "--- Exit code: $?, Suspicious constructs found!"; fi
+          if go vet ./...; then printf -- '--- \U0001f7e9 No suspicious constructs found.'; else printf "--- \U0001f7e5 Exit code: $?, Suspicious constructs found!"; fi
       - name: Lint
         uses: golangci/golangci-lint-action@v9
       - name: Unit Tests
         run: |
           echo '--- Begin unit testing'
-          if CGO_ENABLED=0 go test ./...; then echo '--- Unit tests passed.'; else echo "--- Exit code: $?, Unit tests failed!"; fi
+          if CGO_ENABLED=0 go test ./...; then printf -- '--- \U0001f7e9 Unit tests passed.'; else printf -- "--- \U0001f7e5 Exit code: $?, Unit tests failed!"; fi
